### ISSUE TITLE
Add ignore_extractions logic to pattern, ai, lookup extractions

### ISSUE THREAD

**Issue by himynamesdave** [muchdogesec/txt2stix#22]
When i run a command like

```
(txt2stix-venv) dgreenwood@Davids-MBP-2 txt2stix % python3 txt2stix.py \
        --relationship_mode ai \
        --input_file tests/inputs/manually_generated_reports/basic_relationship.txt \
        --name 'Test 4.0.1 Basic AI relationships' \
        --tlp_level clear \
        --confidence 100 \
        --use_extractions pattern_ipv4_address_only,pattern_domain_name_only,lookup_malware,pattern_email_address
```

The input text was

```
fakedomain.com resolves to 1.1.1.1.

fakedomain.com has been known to distribute revil malware sent in payloads via email from the address fakedomain@email.com
```

Here 

email.com (pattern_domain_name_only) and fakedomain@email.com (pattern_email_address) are extracted.

Really we only want the email address fakedomain@email.com extracted (in most cases).

To allow for the user to ignore these extractions we should add another list key to the extractions config files.

e.g.

```
pattern_email_address:
  type: pattern
  name: 'Email addresses'
  description: 'Extracts emails with valid TLDs'
  notes: 'Uses the Python Validators library. However, this does not check for a valid TLD. Therefore the extraction is then also validated to ensure the end of the domain has a valid TLD, using the Python TLD library.'
  created: 2020-01-01
  modified:  2020-01-01
  created_by: DOGESEC
  version: 1.0.0
  test_cases: generic_email_address
  ignore_extractions:
    - pattern_domain_name_only
    - pattern_domain_name_subdomain
  stix_mapping: email-addr
```

in this example, any string extracted for pattern email should not be analysed for 

    - pattern_domain_name_only
    - pattern_domain_name_subdomain

these extraction types would work elsewhere in the text, just not in the values extracted for pattern_email_address
